# Generated by Django 5.0.6 on 2024-10-30 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salons', '0001_initial'),
        ('services', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='barbers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.barber'),
        ),
        migrations.AddField(
            model_name='salon',
            name='services',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salons_list', to='services.services'),
        ),
        migrations.AddField(
            model_name='salon',
            name='sosial_links',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.sosiallinks'),
        ),
    ]
