# Generated by Django 5.0.6 on 2024-10-30 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='image',
            field=models.ImageField(upload_to='media/salons'),
        ),
    ]
