# Generated by Django 5.0.6 on 2024-10-30 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0004_alter_salon_services'),
        ('services', '0011_alter_barberservices_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salon',
            name='services',
        ),
        migrations.AddField(
            model_name='salon',
            name='services',
            field=models.ManyToManyField(blank=True, null=True, related_name='salons_list', to='services.salonservices'),
        ),
    ]
