# Generated by Django 5.0.6 on 2024-10-31 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0008_salon_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salon',
            name='password',
        ),
    ]
