# Generated by Django 5.0.6 on 2024-10-31 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0010_remove_salon_sosial_links_salon_instagram_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salon',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
