# Generated by Django 5.0.6 on 2024-10-30 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_services_barbers_remove_services_salons_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='image',
            field=models.ImageField(upload_to='media/barber'),
        ),
        migrations.AlterField(
            model_name='barber',
            name='services',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barbers_list', to='services.barberservices'),
        ),
    ]
