# Generated by Django 5.0.6 on 2024-10-30 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_alter_barberservices_price'),
        ('users', '0002_alter_barber_image_alter_barber_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barber',
            name='services',
        ),
        migrations.AddField(
            model_name='barber',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='barbers_list', to='services.barberservices'),
        ),
    ]
