# Generated by Django 5.0.6 on 2024-10-30 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0007_remove_salon_barbers_salon_barbers'),
        ('users', '0003_remove_barber_services_barber_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barber',
            name='salons',
        ),
        migrations.AddField(
            model_name='barber',
            name='salons',
            field=models.ManyToManyField(blank=True, related_name='barbers_in_salon', to='salons.salon'),
        ),
    ]
