# Generated by Django 5.0.6 on 2024-10-31 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_barber_salons_barber_salons'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='password',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
