# Generated by Django 5.0.6 on 2024-10-31 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_barber_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='password',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
