# Generated by Django 5.0.6 on 2024-10-31 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_barber_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/barber'),
        ),
    ]
