# Generated by Django 5.0.6 on 2024-10-31 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0012_salon_password'),
        ('users', '0021_remove_barber_sosial_links_barber_instagram_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='salon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='salons.salon'),
            preserve_default=False,
        ),
    ]
