# Generated by Django 5.0.6 on 2024-10-31 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_barber_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
