# Generated by Django 5.0.6 on 2024-10-30 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0004_alter_salon_services'),
        ('services', '0003_remove_services_barbers_remove_services_salons_and_more'),
        ('users', '0002_alter_barber_image_alter_barber_services'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Services',
        ),
    ]
