# Generated by Django 5.0.6 on 2024-10-30 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_pricecurency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salonservices',
            name='price_curency',
            field=models.ForeignKey(blank=True, default='₼', null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.pricecurency'),
        ),
    ]
