# Generated by Django 5.0.6 on 2024-10-30 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_salonservices_price_curency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salonservices',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=5, default='Ödənişsiz', max_digits=10, null=True),
        ),
    ]
