# Generated by Django 5.0.6 on 2024-10-30 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_salonservices_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salonservices',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default='Ödənişsiz', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='salonservices',
            name='price_curency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.pricecurency'),
        ),
    ]
