# Generated by Django 5.0.6 on 2024-10-30 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_salonservices_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barberservices',
            name='barber',
        ),
        migrations.RemoveField(
            model_name='salonservices',
            name='salons',
        ),
    ]
