# Generated by Django 5.0.6 on 2024-10-30 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_remove_barberservices_barber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barberservices',
            name='price_curency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.pricecurency'),
        ),
    ]
