# Generated by Django 5.0.6 on 2024-10-30 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_alter_barberservices_price_curency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barberservices',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
